### PR TITLE
Issue 5 create simple fastapi server

### PR DESCRIPTION
**Pull request by najeebib**

### CODE REVIEW

**Review by yishain11 — CHANGES_REQUESTED** [review]
code is ok, but how do I run the server?
when im in the root dir of the repo and i try to run:
python server/server.py it doesnt work. does it work for you?

**Comment by najeebib** [comment]
it works if you run this command
uvicorn server.server:app

**Comment by najeebib** [comment]
python -m server.server
this one works

**Review by yishain11 — CHANGES_REQUESTED** [review]
please add instructions on how to start the server (install req, go to root folder, run command X) to readme

**Pull request merged**
